spring:
  application:
    name:  Phorest Salon Ghodrat Version
    version: ${version}
  profiles:
    active: LOCAL
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:salon
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: false
  mvc:
    throw-exception-if-no-handler-found: false
  servlet:
    multipart:
      max-file-size:  1MB
      max-request-size: 10MB
server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT:8080}
  compression:
    enabled: true
#Initialize the app with the CSV files that provided with the challenge
#preload: false
